### ISSUE TITLE
My gateway stops working after a few days

### ISSUE THREAD

**Issue by jfmateos** [things4u/ESP-1ch-Gateway-v5.0#10]
Hi, I have a gateway powered through a phone charger.
The gateways works flawlessly for days and then it just disappear from the wifi network.

How could i troubleshoot this issue?
Does the software store any statistical information about the processor status?
Could the gateway be automatically reset every few days? watchdog?

**Comment by platenspeler** [comment]
Thanks, I think that the latest version (which I'm trying to get on line this week) will solve WiFi issues. It appears that the ESP8266 has a bug when WiFi.begin() is executed. It does not forget the last WiFi access point connected to, but also does not allow reconnecting to that Access Point. The patch does correct this.
So when the gateway for whatever reason looses the connection for a short time it will now reconnect to the last Access Point. The latest version solves that.

**Comment by platenspeler** [comment]
Latest version 5.0.8 survives a WiFi gateway error.
