### ISSUE TITLE
Timezone & DST

### ISSUE THREAD

**Issue by kylix34** [things4u/ESP-1ch-Gateway-v5.0#12]
Is there any way to have the Daylight Save Time option too? Otherwise the hour displayed by the gateway is not always correct.

**Comment by platenspeler** [comment]
In the ESP-sc-gway.h you can set it as a parameter.
Unfortunately automatic DST is not yet provided.

Maarte

**Comment by kylix34** [comment]
Could you include this library for the automatic DST: https://github.com/neptune2/simpleDSTadjust ?

**Comment by platenspeler** [comment]
Good point, thanks. Will have a look for next release.
