### ISSUE TITLE
Problem with lon and lat near Greenwich or Ecuador

### ISSUE THREAD

**Issue by jfmateos** [things4u/ESP-1ch-Gateway-v5.0#18]
The foa function removes the minus sign for values like -0.####
(Detected by Ximo Catalá)
You can solve iy adding the following line:
![imagen](https://user-images.githubusercontent.com/29097198/39811484-23897f26-5389-11e8-9170-59a2d92083a1.png)

**Comment by platenspeler** [comment]
Thank you. I have inplemented in my latest release and will include in version 5.2.1

Maarten
