### ISSUE TITLE
No RXDONE

### ISSUE THREAD

**Issue by Algram** [things4u/ESP-1ch-Gateway-v5.0#20]
Hello,
once my gateway starts up successfully and I enable debug mode, it gets spammed with the following messages:

`S_RX:: no RXDONE, RXTOUT, HEADER:: I=  --  , F=0, SF=9, E=0, S=RX  , t=69997239`

What do those mean?

**Comment by platenspeler** [comment]
This is a condition that should not happen. It means that we are in receiving state but did receive another interrupt than RXDONE (reception complete) or RXTOUT (timeout).

What version of the software are you running? Please upgrade to the latest version and try again. This is the version I have running on all my Wemos D1 mini gateways and the other ones.

Thanks,

Maarten

**Comment by platenspeler** [comment]
So please check the board that you are using and compare to ESP gateway.h 
It looks like you have a pin problem.
