### ISSUE TITLE
Serial output not in Serial monitor

### ISSUE THREAD

**Issue by dbuggz** [things4u/ESP-1ch-Gateway-v5.0#26]
At the start of setup() there are some Serial.println statements that do not get displayed on the serial monitor.

```
#ifdef ESP32
	Serial.println(F("ESP32 defined"));
#endif
#ifdef ARDUINO_ARCH_ESP32
	Serial.println(F("ARDUINO_ARCH_ESP32 defined"));
#endif
```

the 
`Serial.begin(_BAUDRATE);            // As fast as possible for bus`
needs to be before them, e.g about line 1227 of ESP-sc-gway.

**Comment by platenspeler** [comment]
Thanks! done.
