### ISSUE TITLE
ESP32 WiFi.begin

### ISSUE THREAD

**Issue by dbuggz** [things4u/ESP-1ch-Gateway-v5.0#27]
Around line 1301... 
```#if ESP32_ARCH==1
	WiFi.setHostname( hostname );
        Serial.println(WiFi.getHostname() );
   #else
```
does not produce the expected output (esp8266-xx xx xx). 
Serial Monitor shows 
```
Host espressif WiFi Connected
```
I believe this is due to there being no WiFi.begin()

 Adding `WiFi.begin()` after `	WiFi.mode(WIFI_STA);` at about line 1283 produces the expected result.
```Host esp8266-4cab5c WiFi Connected```

I'm using an ESP32, so this should "ESP32-4cab5c", so: 
```
#if ESP32_ARCH==1
  sprintf(hostname, "%s%02x%02x%02x", "esp32-", MAC_array[3], MAC_array[4], MAC_array[5]);
  WiFi.setHostname( hostname );
#else
  sprintf(hostname, "%s%02x%02x%02x", "esp8266-", MAC_array[3], MAC_array[4], MAC_array[5]);
  wifi_station_set_hostname( hostname );
#endif
```

p.s. Sorry I'm new to github, so I'm not sure how I should push changes through back to you.

Dave

**Comment by platenspeler** [comment]
Hi,

Thanks for your help! Indeed it seems that WiFi.begin should be called before setting the hostname. However, I do set the hostname in "WlanConnect()" but that function i called after setting the hostname.
By placing the WlanConnect part before setting the hostname all works as expected.

I will update the code shortly.

Maarten
