### ISSUE TITLE
downlink / send message to node

### ISSUE THREAD

**Issue by halukmy** [things4u/ESP-1ch-Gateway-v5.0#28]
i have connected gateway with lmic node so how can i send downlink message to my node via gateway?

i use mqtt and loraserver.io for downlink but there is no sending any message to my node..

is anybody use it?

**Comment by platenspeler** [comment]
I made an error in version 5.2 and a few earlier version with the downlink code. I'm testing a solution now.
Unfortunately this has nothing to do with MQTT. You best do this using the TTN Console.

**Comment by platenspeler** [comment]
This is a double from your other message.
