### ISSUE TITLE
Missing Bracket in _Wifi.ino (will not compile if wifimanager=1)

### ISSUE THREAD

**Issue by maartenva84** [things4u/ESP-1ch-Gateway-v5.0#34]
Hi
you are missing a bracket in _Wifi.ino on rule 72

	if **(**  (debug >=0 ) && ( pdebug & P_MAIN )) {

Is will not compile you enable wifimanager.

**Comment by platenspeler** [comment]
Stupid of me. I will correct in next version.
Thanks!

**Comment by platenspeler** [comment]
Done
