### ISSUE TITLE
Config moved from ESP-sc-gatway.h to config.h

### ISSUE THREAD

**Issue by cimm** [things4u/ESP-1ch-Gateway-v5.0#35]
Not tested it myself but found someone [mentioning](https://www.thethingsnetwork.org/forum/t/lorago-dock-first-impression/10700) the README is not up-to-date and the config now lives in `config.h` and not in `ESP-sc-gway.h`.

Opening this issue if anyone else would have the same problem.

**Comment by platenspeler** [comment]
I do not understand what you mean...

**Comment by halukmy** [comment]
me neither

**Comment by cimm** [comment]
I found a [comment](https://www.thethingsnetwork.org/forum/t/lorago-dock-first-impression/10700?u=cimm) in the forum linked in my first message:

> The instructions on github is not 100% up-to-date with the actual software, eg. the configuration is in config.h and not ESP-sc-gway.h.

I thought the readme was out of date and could use a little refresh but I am probably missing the point. Sorry.
