### ISSUE TITLE
Repeatedly resetting after trying to get NTP time

### ISSUE THREAD

**Issue by iPAS** [things4u/ESP-1ch-Gateway-v5.0#37]
FYI the problem and solution.

The TTGO ESP32 LoRa kept resetting after boot due to the problem that it cannot found an IP address of NTP server. 
The printed serial message was shown:

> Setup:: ERROR hostByName NTP
> abort() was called at PC 0x400d9c22 on core 1
> 
> Backtrace: 0x4008fe80:0x3ffb1ee0 0x40090083:0x3ffb1f00 0x400d9c22:0x3ffb1f20 0x400db652:0x3ffb1f40 0x40137d23:0x3ffb1fa0
> 
> Rebooting...
> 

I fix this problem by setting DNS to 8.8.8.8 as the following:
	
```
ip_addr_t d;
d.type            = IPADDR_TYPE_V4;
d.u_addr.ip4.addr = static_cast<uint32_t>((uint32_t)0x08080808); // Google DNS
dns_setserver(0, &d);


if (!WiFi.hostByName(NTP_TIMESERVER, ntpServer))		// Get IP address of Timeserver
{
	die("Setup:: ERROR hostByName NTP");
...
```

**Comment by hotzenklotz** [comment]
I have the same error with Wemos D1 Mini Pro board.

**Comment by MadeInHelpup** [comment]
I seem to have a similiar problem with my TTGO v2 board.  Some seconds after bootup and availability of the web interface the board reboots. In the serial monitor I'm getting this log:

MAC: xxxx , len=17
WlanConnect:: Init para 0
0:1. WiFi connect SSID=xxxxx, pass=xxxxxxx
WlanCStatus:: CONNECTED toWSWLN_D
Host esp32-634dbc WiFi Connected to WSWLN_D on IP=192.168.2.139
Local UDP port=1700
Connection successful
Gateway ID: xxxxxx, Listening at SF9 on 868.10 Mhz.
setupOta:: Started
Ready
IP address: 192.168.2.139
Time: Monday 20:17:40
Gateway configuration saved
WWW Server started on port 80
--------------------------------------
readUdp:: NTP msg rcvd
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x400ee673  PS      : 0x00060d30  A0      : 0x800ef06a  A1      : 0x3ffbce20  
A2      : 0x00000000  A3      : 0x00000010  A4      : 0x00000091  A5      : 0x3ffbf0c4  
A6      : 0x3ffbe53c  A7      : 0x3ffbe5cd  A8      : 0x800ee1aa  A9      : 0x3ffbce00  
A10     : 0x00000001  A11     : 0x3ffbe53c  A12     : 0x00000091  A13     : 0x00000001  
A14     : 0x00060923  A15     : 0x00000010  SAR     : 0x00000010  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000004  LBEG    : 0x4000c349  LEND    : 0x4000c36b  LCOUNT  : 0x00000000  

Backtrace: 0x400ee673:0x3ffbce20 0x400ef067:0x3ffbcea0 0x400ef0c6:0x3ffbced0

Rebooting...

I've added the ip and port to the serial out and it seems to be the ntp server: 193.175.73.151, port 123

Unfortunatelly adding the DNS didn't resolve the issue.

Any kind of help appreciated..

**Comment by iPAS** [comment]
Thank you all for sharing. 
Finally I found that the DNS assignment is not help the gateway in solving a host name.
I guess because of some security issue on the network -- not allowing the DNS query forwarding.
So, in my setup private network, the DHCP server has to assign a DNS server of the office network to the ESP32 LoRa gateway.

The setup network comprises of:
- Linux (of course),
- HostAPd, and
- DHCPd with a configuration line:
   > ...
   > option domain-name-servers <My office DNS IP>;
   > ...

After testing so far, nothing recurrently go wrong again.

**Comment by MadeInHelpup** [comment]
Do I understand correct: You've changed settings in your DHCP server that solved the issue? 
I can't really believe that, as there is a not handled exception in the code?

Or did you changed something in the code?

**Comment by iPAS** [comment]
Right!
In my opinion, the problem on LoRa ESP32 gateway causes from a reasons:
1) The gateway does **not receive a DNS-server address** via DHCP mechanism, or
2) The gateway in your own private network **receives a public DNS-server address** (e.g. 8.8.8.8) where your outer organization network does **not allow** the request to other DNS-server.

In conclusion, I believe that the code of LoRa ESP32 gateway has been already correct.
But, configuration of the network might have not been.

**Comment by dksmar** [comment]
Finally worked! there is something wrong with my local LAN DHCP. I have put as secondatry option the SSID of my grandmother's house (1 floor down) and worked! Also when I put my mobile as hotspot with credentials of my house wifi works!

**Comment by platenspeler** [comment]
I will close this issue, as it seems not related to the gateway but to the network/DNS setup.
