### ISSUE TITLE
inDecodes functions Doesn't work

### ISSUE THREAD

**Issue by iApotoxin** [things4u/ESP-1ch-Gateway-v5.0#39]
I think, this function need more parameters.

**Comment by platenspeler** [comment]
Can you please explain? Doesn't work? What does not work? What parameter is missing?

**Comment by iApotoxin** [comment]
int inDecodes(char * id) {

	uint32_t ident = ((id[3]<<24) | (id[2]<<16) | (id[1]<<8) | id[0]);

	int i;
	for ( i=0; i< (sizeof(decodes)/sizeof(codex)); i++) {
		if (ident == decodes[i].id) {
			return(i);
		}
	}
	return(-1);
}

![screen shot 2561-07-11 at 08 48 40](https://user-images.githubusercontent.com/13836766/42546368-513619e0-84e7-11e8-829b-9789abf516ed.png)
In _utils decodes and codex don't declared in function.

**Comment by peterkorolev** [comment]
Comment out the function "inDecodes," and set TRUSTED_DECODE in ESP-sc-gway.h to 0.

**Comment by iApotoxin** [comment]
To peterkorolev.
Yes, I solve this issue like yours suggestion. but i think it will be effect to other.
 it's seem works but  gateway can't send data to node. so i don't know this problem is effected from lost inDecode function, is it.

**Comment by platenspeler** [comment]
I do not think that sending data to the node it is related to your first issue. 

For the inDecodes function I have added

#if _LOCALSERVER==1 

It should only be defined and work when _LOCALSERVER is set. I have uploaded the change to github.


Maarten

**Comment by iApotoxin** [comment]
To platenspeler.

Thank You, So i have a question. This example code can forward downlink to node, or not ?

**Comment by platenspeler** [comment]
As far as I know the gateway does send downstream messages correctly. It is a little difficult for me to test as we have quite a few gateways around the house. I plan to test the downstream function on ESP32 again in August.
