### ISSUE TITLE
ERROR hostByName TTN Abort called

### ISSUE THREAD

**Issue by renatocarusos** [things4u/ESP-1ch-Gateway-v5.0#45]
```
Host esp8266-0c3131 WiFi Connected to Pe de Tamarindo on IP=10.0.0.104
Local UDP port=1700
Connection successful
Gateway ID: 600194FFFF0C3131, Listening at SF9 on 903.90 Mhz.
Setup:: ERROR hostByName TTN
Abort called
```
Does anyone know how to solve this and connect?
Ty

**Comment by platenspeler** [comment]
The system cannot get the ip address of your TTN server. What address did you specify for the ttnserver in the ESP-sc-gway.h file?

**Comment by renatocarusos** [comment]
`#define _TTNSERVER "ttn-router-brazil"`
The same in TTN panel.

**Comment by platenspeler** [comment]
I do not think that is a full domain name. Is has to be a hostname including a domain like the example in my code or a fully qualified IP address. The DNS server will never find that host on the internet.

Maarten

**Comment by platenspeler** [comment]
brazil.thethings.network seems to be the host to look for

**Comment by renatocarusos** [comment]
It worked!
![image](https://user-images.githubusercontent.com/39814643/43762709-0dc0a914-99ff-11e8-959c-4d03b2df156b.png)

**Comment by platenspeler** [comment]
Thanks
