### ISSUE TITLE
Only three SF scanning when HOP is ON.

### ISSUE THREAD

**Issue by darkdarkgray** [things4u/ESP-1ch-Gateway-v5.0#46]
It is normal tnat gateway scan all SF when HOP is OFF and only three SF when HOP is ON?

**Comment by platenspeler** [comment]
No it is not. But if your nodes do not send on a single frequency then it might be different.

**Comment by darkdarkgray** [comment]
Do you resolve this problem?

**Comment by platenspeler** [comment]
When the gateway receives on all SF when CAD is on and HOP is off than it works OK for the moment. HOP use is still experimental and I like to get this working, but this is a single channel gateway with a reason. Use of HOP would mean that it is a limited (3 frequencies) but full blown gateway (for less than 5 euro, wouldn't that be nice)

Regards, 
Maarten
