### ISSUE TITLE
use of struct LoraUp  parameter in sensorPacket messageSent

### ISSUE THREAD

**Issue by maurocordioli** [things4u/ESP-1ch-Gateway-v5.0#5]
when we enable GATEWAYNODE , 
 in sensorPacket /_sensor.ino 
the function messageSent is called with may be , an outdated parameter list (using message and message length) instead of use of struct LoraUp  parameter .... 
something like this : ( but I don't know yet the use of other members of the struc, I have just tried my first program from my new ESP32 pair ) 
` 
//MC start
struct   LoraUp LU;
memcpy( LU.payLoad, message, mlength*sizeof(uint8_t) );
LU.payLength= mlength ;
  
    int buff_index = buildPacket(tmst, buff_up,LU,  true);
// old call int buff_index = buildPacket(tmst, buff_up,(uint8_t *) (message), mlength, true);
 //MC end`

**Comment by iotlearner0level** [comment]
Thanks 	maurocordioli for sharing. worked for me!

Great!!

**Comment by platenspeler** [comment]
Thanks for finding this bug! I have patched the latest 5.2.1 version.
