### ISSUE TITLE
ESP32 instruction

### ISSUE THREAD

**Issue by arrowcircle** [things4u/ESP-1ch-Gateway-v5.0#51]
Hey!
I am trying to build single channel gateway, but cant compile project. It requires ESP8266WiFi.h in WiFi manager, but if ESP32 board is loaded it will not load esp8266 libs.
Any ideas how to compile it?

**Comment by JackGruber** [comment]
Hi, 

have you point your Arduino Sketchbook path to your unziped ESP-1ch-Gateway-v5.0 folder with the containing libraries folder?

**Comment by arrowcircle** [comment]
@JackGruber I figured out how to compile it, but there are changed in the code that needed to be done to compile successfully. As I remember, its about webserver and some libs.

**Comment by gabrielklein** [comment]
https://github.com/kersing/ESP-1ch-Gateway-v5.0 but it's an older version.

**Comment by gutembergsa** [comment]
> @JackGruber I figured out how to compile it, but there are changed in the code that needed to be done to compile successfully. As I remember, its about webserver and some libs.

can you explain what "changes"? having same issue here

**Comment by platenspeler** [comment]
Is there something I must fix, or can you compile now?
I know that in version 6 most issues are fixed, but be sure to include the right version 6 of ArduinoJson.

**Comment by platenspeler** [comment]
I will close this issue.
