### ISSUE TITLE
Compile problem

### ISSUE THREAD

**Issue by elsabz** [things4u/ESP-1ch-Gateway-v5.0#53]
Hi i have problem wen i compiling...
DNSServer.h: No such file or directory
OS: Windows 10
Arduino IDE 1.8.7
esp32 platform is installed and updated
Any suggestion?

**Comment by rolfz** [comment]
HI
I also get compiler problems trying to compile the code for TTGO ESP32 LORA board. I get  'HTTPClient' has not been declared error, any idea hat could be missing ?

**Comment by richard-ubi** [comment]
I think lib was not included

**Comment by platenspeler** [comment]
Closing this one. Problem seems to be solved.
