### ISSUE TITLE
Gatway hangs irremediably after some time...

### ISSUE THREAD

**Issue by alexbn71** [things4u/ESP-1ch-Gateway-v5.0#55]
I've tried this software for days with two kind of hardware, one "SparkFun LoRa Gateway - 1-Channel (ESP32)" and one "TTGO LORA32" and the result is the same... after few hours or at most 1 or 2 days the gateways stop running. The web server does not repond... the serial consol does not show anything, like a reset or any other error (and obviously the TTN console shows the gateway no more connected)

Can you suggest me how to set properly the debug variables to try to catch what's going wrong?

**Comment by fabioetec** [comment]
I have the same problem, did you find any solution?

Thank you
Fabio

**Comment by nicolasimeoni** [comment]
see this pull request: 
https://github.com/things4u/ESP-1ch-Gateway-v5.0/pull/61
it fixes this problem
Nicola

**Comment by platenspeler** [comment]
I did merge the lramodem.ini file. Seems this issue is resolved.
