### ISSUE TITLE
Is it possible to use this gateway con a E32-915T30D or E32-915T20D Lora modules?

### ISSUE THREAD

**Issue by ctripodi** [things4u/ESP-1ch-Gateway-v5.0#60]
Hello, a few days ago I received some E32-915T30D and E32-915T20D Lora modules. I'd like to use this modules with a NODEMCU to build a LoraGateway. Unfortunatelly, I could not see how connect this modules (GPIO Pin Out) to be used with this great proyect.
Can you please help me? Is it possible?
Thank you. Cristian

**Comment by yezids** [comment]
hello friend, follow the link

http://things4u.github.io/UserGuide/One%20Channel%20Gateway/Installation%205.html

**Comment by platenspeler** [comment]
https://things4u.github.io/Projects/SingleChannelGateway/UserGuide/Introduction%206.html

I changed the location
