### ISSUE TITLE
Unknown transceiver: Abort called

### ISSUE THREAD

**Issue by chrimohr** [things4u/ESP-1ch-Gateway-v5.0#96]
I've got everything configured but still getting this error.

```
Unknown transceiver=FF, pins.rst =0, pins.ss  =16, pins.dio0 =15, pins.dio1 =15, pins.dio2 =15
Abort called
```
Looked through the other solved issues but did not find an solution...

**Comment by tmallwitz** [comment]
@chrimohr Had the same issue. My Board has a different pin layout. What board are you using?

I have the TTGO ESP32-Paxcounter LoRa32 V2.1 _ 1,6

for that this work:

#elif _PIN_OUT==6
// ----------------------------------------------------------------------------
// For LILYGO®TTGO ESP32-Paxcounter LoRa32 V2.1 1,6
//
// SCK  == GPIO5/ PIN5
// SS   == GPIO18/PIN18 CS
// MISO == GPIO19/ PIN19
// MOSI == GPIO27/ PIN27
// RST  == GPIO14/ PIN14
struct pins {
  uint8_t dio0=26;    // GPIO26 / Dio0 used for one frequency and one SF
  uint8_t dio1=26;    // GPIO26 / Used for CAD, may or not be shared with DIO0
  uint8_t dio2=26;    // GPIO26 / Used for frequency hopping, don't care
  uint8_t ss=18;      // GPIO18 / Dx. Select pin connected to GPIO18
  uint8_t rst=23;     // GPIO0 / D3. Reset pin not used 
} pins;
#define SCK 5       // Check
#define MISO 19       // Check
#define MOSI 27       // Check
#define RST 23        // Check
#define SS 18

**Comment by chrimohr** [comment]
It's a DIY PCB - had some traces mixed up
